### ISSUE TITLE
Syntax error macroexpanding clojure.core/ns at (csi/technician.clj:1:1)

### ISSUE THREAD

**Issue by pzygielo** [pzlc/csi#1]
Upgrading [clojure](https://github.com/clojure/clojure) from [1.9.0](https://github.com/clojure/clojure/releases/tag/clojure-1.9.0) to [1.10.0-beta3](https://github.com/clojure/clojure/releases/tag/clojure-1.10.0-beta3) breaks the build with following
```
Exception in thread "main" Syntax error macroexpanding clojure.core/ns at (csi/technician.clj:1:1). Cause: Call to clojure.core/ns did not conform to spec.
	at clojure.lang.Compiler.checkSpecs(Compiler.java:6970)
	at clojure.lang.Compiler.macroexpand1(Compiler.java:6986)
	at clojure.lang.Compiler.macroexpand(Compiler.java:7066)
	at clojure.lang.Compiler.compile1(Compiler.java:7692)
	at clojure.lang.Compiler.compile(Compiler.java:7774)
	at clojure.lang.RT.compile(RT.java:413)
	at clojure.lang.RT.load(RT.java:458)
	at clojure.lang.RT.load(RT.java:426)
	at clojure.core$load$fn__6648.invoke(core.clj:6071)
	at clojure.core$load.invokeStatic(core.clj:6070)
	at clojure.core$load.doInvoke(core.clj:6054)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invokeStatic(core.clj:5873)
	at clojure.core$compile$fn__6653.invoke(core.clj:6081)
	at clojure.core$compile.invokeStatic(core.clj:6081)
	at clojure.core$compile.invoke(core.clj:6073)
	at clojure.lang.Var.invoke(Var.java:384)
	at clojure.lang.Compile.main(Compile.java:70)
Caused by: clojure.lang.ExceptionInfo: Call to clojure.core/ns did not conform to spec. {:clojure.spec.alpha/problems [{:path [], :reason "Extra input", :pred (clojure.spec.alpha/cat :docstring (clojure.spec.alpha/? clojure.core/string?) :attr-map (clojure.spec.alpha/? clojure.core/map?) :ns-clauses :clojure.core.specs.alpha/ns-clauses), :val ((:import (javax.ejb ActivationConfigProperty MessageDriven) (javax.jms.Message))), :via [:clojure.core.specs.alpha/ns-form], :in [1]}], :clojure.spec.alpha/spec #object[clojure.spec.alpha$regex_spec_impl$reify__2509 0x5ddf0d24 "clojure.spec.alpha$regex_spec_impl$reify__2509@5ddf0d24"], :clojure.spec.alpha/value (csi.technician (:import (javax.ejb ActivationConfigProperty MessageDriven) (javax.jms.Message))), :clojure.spec.alpha/args (csi.technician (:import (javax.ejb ActivationConfigProperty MessageDriven) (javax.jms.Message)))}
	at clojure.spec.alpha$macroexpand_check.invokeStatic(alpha.clj:705)
	at clojure.spec.alpha$macroexpand_check.invoke(alpha.clj:697)
	at clojure.lang.AFn.applyToHelper(AFn.java:156)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.lang.Var.applyTo(Var.java:705)
	at clojure.lang.Compiler.checkSpecs(Compiler.java:6968)
```
1. [1.10.0-alpha6](https://github.com/clojure/clojure/releases/tag/clojure-1.10.0-alpha6) is fine, build breaks at https://github.com/clojure/clojure/commit/db94999b543effe0be04ca4ed53d8e699674cfff.
1.  Upgrade of [spec.alpha](https://github.com/clojure/spec.alpha) is fine, with change of [core.specs.alpha](https://github.com/clojure/core.specs.alpha) build breaks.
1.  Bisected to https://github.com/clojure/core.specs.alpha/commit/938c0a9725a284095baa2387dff1a29c3f1e26ac.

**Comment by pzygielo** [comment]
Maybe [this RegEx](https://github.com/clojure/core.specs.alpha/commit/938c0a9725a284095baa2387dff1a29c3f1e26ac#diff-417569c12a3a6e0bdd635543f162679aR140).
